### ISSUE TITLE
Invalid SPMetadata result

### ISSUE THREAD

**Issue by AlexeySafronov** [tngan/express-saml2#32]
Hi! @tngan, I found the problem in metadata method in the code [SPMetadata.js#L98](https://github.com/tngan/express-saml2/blob/master/lib/SPMetadata.js#L98)

Look at this

```javascript
const conf = {
                        sp: {
                            entityID: metaUrl,
                            nameIDFormat:["urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"],
                            assertionConsumerService:[{
                                Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
                                Location: acsUrl,
                                Index: 1
                            },{
                                Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
                                Location: acsUrl,
                                Index: 2
                            }],
                            singleLogoutService:[{
                                Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
                                Location: sloUrl,
                                Index: 1
                            },{
                                Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
                                Location: sloUrl,
                                Index: 2
                            }]
                        }
};
const sp = new saml.ServiceProvider(conf.sp);

const xml = sp.getMetadata();
```
I get this
``` xml
<EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:assertion="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="http://localhost:3000/sso/metadata">
<SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
</NameIDFormat>
<SingleLogoutService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:3000/sso/slo/callback"/>
<SingleLogoutService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:3000/sso/slo/callback"/>
<AssertionConsumerService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:3000/sso/acs"/>
<AssertionConsumerService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:3000/sso/acs"/>
</SPSSODescriptor>
</EntityDescriptor>
```
xml param data is not valid if i try to validate it in [www.samltool.com](https://www.samltool.com/validate_xml.php)

`
Line: 1 | Column: 0  --> Element 'EntityDescriptor': No matching global declaration available for the validation root.
`

"md" prefix must be in any xml tag, like this 
``` xml
<md:EntityDescriptor  xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"" />
```

or "md" is useless and we must use tags without prefix, like this
``` xml
<EntityDescriptor  xmlns="urn:oasis:names:tc:SAML:2.0:metadata" />
```

**Comment by tngan** [comment]
http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml1x-metadata-os.html

I think SAML v1 uses that expression.

**Comment by AlexeySafronov** [comment]
This variant is valid
```xml
<md:EntityDescriptor entityID="http://localhost:3000/sso/metadata" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
    <md:SPSSODescriptor WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
		<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:3000/sso/slo/callback"/>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
        <md:AssertionConsumerService index="1" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:3000/sso/acs"/>
		<md:AssertionConsumerService index="2" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:3000/sso/acs"/>
    </md:SPSSODescriptor>
</md:EntityDescriptor>
```
and this is valid too

```xml
<EntityDescriptor entityID="http://localhost:3000/sso/metadata" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <SPSSODescriptor WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
		<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:3000/sso/slo/callback"/>
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
        <AssertionConsumerService index="1" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:3000/sso/acs"/>
		<AssertionConsumerService index="2" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:3000/sso/acs"/>
    </SPSSODescriptor>
</EntityDescriptor>
```

**Comment by AlexeySafronov** [comment]
Also i found: 

- SingleLogoutService tag must be before NameIDFormat tag
- SingleLogoutService must be only one
- AssertionConsumerService index must be greater then 0

**Comment by AlexeySafronov** [comment]
This code always return index=0 [SPMetadata.js#L81](https://github.com/tngan/express-saml2/blob/master/lib/SPMetadata.js#L81)

I this this variant is better:

```javascript

var _indexCount = 0;
assertionConsumerService.forEach(function(a) {
                var _attr = {};
                
                if(a.isDefault) {
                    _attr.isDefault = true;
                }
                _attr.index = (++_indexCount).toString();
                _attr.Binding = a.Binding;
                _attr.Location = a.Location;
                SPSSODescriptor.push({
                    AssertionConsumerService: [{
                        _attr: _attr
                    }]
                });
            });
```

**Comment by tngan** [comment]
@AlexeySafronov 

+ `SingleLogoutService tag must go before NameIDFormat tag`, it's interesting, actually order in xml node is for faster and easier parsing, i relax this constraint in this module, is it specified in documentation ?
+ SingleLogoutService can be zero or more. Ref P.16 of 43.
+ index can be 0 according to the standard metadata sample. Ref P.25 of 43 

Ref is [here](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf)

**Comment by AlexeySafronov** [comment]
@tngan 

> SingleLogoutService tag must go before NameIDFormat tag, it's interesting, actually order in xml node is for faster and easier parsing, i relax this constraint in this module, is it specified in documentation ?

I could not find this in specification, but samltool return this 
`
Line: 4 | Column: 0  --> Element '{urn:oasis:names:tc:SAML:2.0:metadata}SingleLogoutService': This element is not expected. Expected is one of ( {urn:oasis:names:tc:SAML:2.0:metadata}NameIDFormat, {urn:oasis:names:tc:SAML:2.0:metadata}AssertionConsumerService ).
`

The standard metadata sample Ref P.25 of 43 has this order too.

**Comment by tngan** [comment]
@AlexeySafronov I am open to accept any pull request and this change is also fine to me, and currently this module only tests with OneLogin service.

**Comment by AlexeySafronov** [comment]
@tngan 
> SingleLogoutService tag must go before NameIDFormat tag, it's interesting, actually order in xml node is for faster and easier parsing, i relax this constraint in this module, is it specified in documentation ?

I found [onelogin issue](https://github.com/onelogin/php-saml/issues/54) about order. Now I'm trying to use your lib with [shibboleth](https://wiki.shibboleth.net/confluence/display/CONCEPT/MetadataForSP) and there is the order like this

> The order of all this information is significant, which you can refer to the schema for, but the most common elements included would be present in the following order:
```xml

- <md:KeyDescriptor> (can be omitted, but rarely)
- <md:SingleLogoutService> (if any)
- <md:NameIDFormat> (if any)
- <md:AssertionConsumerService> (always at least one)
- <md:AttributeConsumingService> (rare today, but good practice to include)

```

Thats why samltool does invalidate metadata.

**Comment by tngan** [comment]
Yes, depending on their xml parser. I think it would be good to make it flexible, then we can customize the order depending on different identity provider, and extend our `getMetadata` method. I will mark it as a feature ticket for this since the roadmap for this library is to support more identity providers.

If not using our metadata generator, the default template can also be customized right now.

**Comment by tngan** [comment]
It's closed since patches are made and new thread is created for the related issue.
