### ISSUE TITLE
Feature request - allow specifying cer/pem/xml strings instead of files.

### ISSUE THREAD

**Issue by sebakerckhof** [tngan/express-saml2#42]
Some systems may want to store key & cer files in a database instead of on disk.
It would be useful if we could create IDPs/SPs with parameters like:
`signingCert` \ `encryptCertFile` \ `privateKey` \ `encPrivateKey` 
instead of only 
`signingCertFile` \ `encryptCertFile` \ `privateKeyFile` \ `encPrivateKeyFile`

Same thing for XML. Now you have to option to pass a file path string, or a config object. It would be great if you could also pass a raw xml string.

**Comment by tngan** [comment]
@sebakerckhof What do you mean by xml string of cert/key ? It would be good to provide some examples before we start working on it, just try to make it clear for delivery.

**Comment by sebakerckhof** [comment]
Well, there's a couple of separate things here.

There's the cert and key files and there's the metadata xml.

Let's take the metadata xml as an example:
Currently you can specify the metadata either as a file path to an xml file or you can give a configuration object which is then transformed to xml in the Metadata subclass (e.g. https://github.com/tngan/express-saml2/blob/master/lib/SPMetadata.js#L96 ).
E.g. option 1 -> passing in the metadata xml filepath:
`new IdentityProvider('../metadata/onelogin_metadata_486670.xml');`

E.g. Option 2 ->. passing in the metadata as an object
```
new IdentityProvider({
 entityID:'https://...',
 nameIDFormat:[...],
...
});
```

However, I'm asking if we could also let the developer pass in raw xml, like:

```
new IdentityProvider(`
<EntityDescriptor ID="SMa4fd5378c57fa016d03c6b27a8e0cf6f99ed2073b" entityID="http://localhost:3001/sso/metadata/369550"
 xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <IDPSSODescriptor WantAuthnRequestsSigned="true"
     ID="SM14a93e72cb19411b4fc4eec882c98b12dbf55cea68e"
     protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    ...
    </IDPSSODescriptor>
</EntityDescriptor>
`);
```

In fact the Metadata class already has a property `isXML` for this ( https://github.com/tngan/express-saml2/blob/master/lib/Metadata.js#L23 ). But this is not exposed when creating Identity/Service providers. 

The advantage is that you can now use it for more use cases e.g.:
1) Read XML from file and pass it to the library
2) Read XML from URL and pass it to the library
3) Read XML from database and pass it to the library

IMO, reading a file is so easy in Node, this library should not do it for the developer. If the developer wants to get the metadata from a file, it's easy enough to do yourself. That way the developer has to add 1 line of code, but in turn he gets more flexibility as in the use cases described above.

Same thing for cert and pem files.

**Comment by tngan** [comment]
Well, we can simplify the issue to directly import entire context, one more thing is to detect which is xmlstring or filestring before the instance is being instantiated. 

I think it could be in v2, right now unless critical bugs are found in v1 and its example, otherwise, all new features and enhancements will not be in v1 anymore.

**Comment by sebakerckhof** [comment]
I agree this is for v2.

For the detection. Either you just let the developer specify this (e.g. by passing the `isXML` variable around). Or you just leave out the file reading altogether and require the developer to do this. That way the library only accepts XML strings or Config objects.

**Comment by tngan** [comment]
Let me close this thread and move to the general one.
