### ISSUE TITLE
Follow general callback style

### ISSUE THREAD

**Issue by sebakerckhof** [tngan/express-saml2#43]
Although not really a requirement, it's somewhat an unwritten rule for callback signatures to follow `(error, result)`. This makes it easy to use them with flow-control libraries or to transform them into promises with libraries like promisify. 

There are several callbacks in this library which do not follow this style, like:
https://github.com/tngan/express-saml2/blob/f5c19bdd3d12d4a6c818dc87eef4e3b48c155897/lib/RedirectBinding.js#L74

Even if they can't return an error it helps in above mentioned aspects to return them as `(null, result)`

**Comment by tngan** [comment]
It makes sense, it could apply to every callbacks in this module.

**Comment by sebakerckhof** [comment]
I can submit a PR for this. I see you added the v1 label to this. This would be a breaking change though, so it might make sense to only do this for v2.

**Comment by tngan** [comment]
@sebakerckhof Let me remove the tag. Feel free to submit a PR for this, and v2 still takes sometime to verify.

**Comment by sebakerckhof** [comment]
Btw, it's not entirely clear to me why some callbacks are there in the first place, e.g.: 
https://github.com/tngan/express-saml2/blob/2.0.0-alpha/src/entity.ts#L243

This seems fully synchronous, so can you help me understand why this works with callbacks?

**Comment by tngan** [comment]
This approach is to relax the rest of the flow to the user, this module aims to compute the essential parts only,  redirect and render work are left to users. In fact, there are no sync process even file reading is in synchronous which is not good enough.

**Comment by sebakerckhof** [comment]
Btw, while we're at it and have the chance to modify the API. Do you think it might make sense to replace some of the callbacks with promises instead?

E.g. I think stuff in `libsaml.ts` like `decryptAssertion` and `encryptAssertion` could benefit from having promises, so later on you can use `async`/`await` much easier (basically without breaking BC in a future release)

**Comment by tngan** [comment]
Yes, that's included in my plan for code revamping after the first step (migrating to typescript) is settled, we can benefit on using async/await directly with typescript. I will open a new thread for code revamping, and we can continue our discussion there.

**Comment by sebakerckhof** [comment]
Okay, I'll close this issue to continue in the general thread.
