### ISSUE TITLE
Code revamping discussion

### ISSUE THREAD

**Issue by tngan** [tngan/express-saml2#45]
**Approved part for code revamping**

- [x] Enhancement for import method of cert/key (#42)
- [x] Standardized callback style (#43)
- [x] Promisify some async processes
- [x] Review of name convention
- [x] Use tslint to do code linting and make git pre-push hook

**Continuous improvement**

- New class for normalizing error and propagate to end users
- Group function arguments as one single object if more than 3

**Comment by sebakerckhof** [comment]
Okay, So 3 proposals on which I could work:
1) Change some of the callbacks to promises where it makes sense, so they can be `awaited` on by babel/typescript users.
2) Convert the remaining callbacks to follow the (error,result) style
3) Don't let the library handle cert/pem/xml files, instead allow passing in the contents directly to allow more flexibility for the library user.

**Comment by tngan** [comment]
@sebakerckhof I have added you to be the collaborator.

**Comment by sebakerckhof** [comment]
Cool. Are you okay on all 3 proposals? If so, I'll create a different branch for each of them. Tackling them one by one in the order they're listed above.

**Comment by tngan** [comment]
Yep, please go ahead. Thanks for your collaboration.

**Comment by sebakerckhof** [comment]
Btw, I also think some method names are misleading.
E.g.: sendLoginRequest doesn't actually send anything. It only creates a request or url. This was somewhat confusing to me.

**Comment by tngan** [comment]
@sebakerckhof We should tackle the name convention, even for variables before releasing v2, I will take care of it.

**Comment by sebakerckhof** [comment]
There are no asynchronous callbacks left since the promise-effort. So I checked that one off too.

**Comment by sebakerckhof** [comment]
@tngan Is there any progress regarding the grouping and/or renaming of functions and their parameters?

If not yet, could I make a proposal in the form of a new branch with just changed method names/signatures. But not yet their implementation. Then you could give feedback on a pull request before we decide on the final ones and refactor the implementation. Or do you rather want to do this yourself?

**Comment by tngan** [comment]
You can make the proposal for that, right now I am in vacation and working on the unit testing (with ava, some commits break the previous test cases but not that serious). By the way, the travis testing pipeline is already fixed so every pull requests will run once in travis before merge.

**Comment by tngan** [comment]
@sebakerckhof The test is ready. The last commit has passed all 59 tests so far we have.
