### ISSUE TITLE
Rewriting idp and sp1 example with vue.js

### ISSUE THREAD

**Issue by tngan** [tngan/express-saml2#46]
Currently, the sample entities are using default express application, we are considering to revamp it using Vue or React, here is the discussion thread.

The design is to separate the frontend view and backend services and use API to control the state and intermediate redirections. Service Provider will allow dynamic configuration, in other words, users can customise which identity provider is being used to do authentication, and other preferences like signature & encrpytion algorithms, binding type, etc.

## **Service Provider**

**Frontend (driven by Vue)**

- [x] Setup vue project with vue-cli
- [x] State management design (Auth, Preference)
- [x] API connector
- [ ] Pages design (Login, SSO, Home)
- [ ] Testings

**API side**

- [ ] POST /login
- [ ] GET /logout
- [ ] POST /configure (configure according to preference)
- [ ] GET /metadata (metadata distribution)
- [ ] POST /acs (service endpoint)
- [ ] GET /spinitsso/:binding (endpoint for initiate sign on from SP)
- [ ] GET /slo (service logout endpoint for redirect binding)
- [ ] POST /slo (service logout endpoint for post binding)

## **Identity Provider**

_Pending_

## **Future**

The examples (both IdP and SP) will eventually become a separate open source product and allow developers to configure and customise according to their preferences.

**Comment by sebakerckhof** [comment]
1 vote for Vue. Mainly because it doesn't require so much tooling & setup like react.

**Comment by tngan** [comment]
I hope to keep the example light-weight. Currently, I am using React+Mobx, and Vue is nearly identical to it and with a easy, configurable client to kickstart a new project (https://github.com/vuejs/vue-cli).

**Comment by sebakerckhof** [comment]
Btw, I would leave one SP as-is. So you have an example of both a SPA and an example of a traditional server-rendered app.

**Comment by tngan** [comment]
I would like put this right after the code revamping tasks are finished.

**Comment by tngan** [comment]
The examples will be separated and maintained in https://github.com/Passify. Then this issue is closed first.
