### ISSUE TITLE
Not working example sp2

### ISSUE THREAD

**Issue by dedpnd** [tngan/express-saml2#57]
Hi!
When trying to log in with es2-IdP to sp2, get this error:
![image](https://cloud.githubusercontent.com/assets/18037236/24201385/eea63cca-0f20-11e7-9ed3-558caf19499b.png)
With SP1 everything is good.

**Comment by tngan** [comment]
@dedpnd Thanks for your report. It's because of incorrect passphrase to open the protected private key file and incorrect certificate in metadata of sp2.

**Comment by tngan** [comment]
@dedpnd Feel free to clone this repo and test it again.
