### ISSUE TITLE
Getting help using the library

### ISSUE THREAD

**Issue by mikevbaker** [tngan/express-saml2#61]
Sorry to use this space to ask for help - I couldn't find any other way to contact.
I've been given the task of adding SAML support to a static website (serverless JavaScript Angular app) and I'm trying to figure out if your library will do the job.
I downloaded the code and looked in the examples for places with require('express-saml2') as shown in the readme, but I can't find any. I've been going over the examples and I believe what I need is what is demonstrated in SP2 with the redirect option (because their SSO already uses the redirect to a login). Of course I'd have to customize the IdP metadata.
Will this lib work with a serverless app? Am I on the right track using SP2 /sso/router.post('/acs' ...)? Is there a bare-bones example of using the saml lib to authenticate a user and redirect to IdP's login?
TIA,
Mike

**Comment by tngan** [comment]
Basically, there are two ways to accomplish SSO, I think what you are talking about is SP-initiated, in other words, you can click a button or directly redirect to IDP login panel if no user is logged in. 

Then IDP will authenticate that user and send back a response to your application endpoint, say /acs, your app will create session for that user if the response is valid. Is that what you are looking for ?

**Comment by mikevbaker** [comment]
Yes, sorry I forgot to mention SP-initiated is what I'm looking for. I need to redirect to the IdP's login page. The login page accepts the SP endpoint in the querystring. i.e.
`https://idpdomain.com/pkmscdsso?https://resourcedomain.com/`
(after login it gets redirected to SP default document)

There currently is no backend to the site. All the content is hard coded into JS using JSON files that are imported at startup. I didn't actually write the site it was handed off to me to set up the server side of things. It's on AWS in S3 storage and the CloudFront CDN. Everything works but we want to add it into the SSO that the client uses. 
I did a prototype of this using Auth0. I was following [this article](https://auth0.com/blog/building-serverless-apps-with-aws-lambda/) (jump down to Aside: Authentication for Serverless Apps with Auth0) But they had a custom js lib that was set up to work with them and I'm looking for a lib that will work with IBM's Tovili Federated Identity Management.

Mike

**Comment by tngan** [comment]
I haven't tried to apply this module in serverless architecture, but I still think it's doable. The /acs endpoint would accept the POST SAML response, so IdP will send back a form including the SAML response to SP.

**Comment by mikevbaker** [comment]
That is my hope. This bring me back around to the first question... is there a sample that uses the lib in the manner described in the readme where the saml object is created with `var saml = require('express-saml')` and then used by something like `saml.ServiceProvider.sendLoginRequest(saml.IdentityProvider, 'redirect', function....`
I'll be giving it a try today and I'll let you know how things turn out.

TIA,
Mike

**Comment by tngan** [comment]
@mikevbaker This is the example for SP-initiated SSO with redirect binding.

https://github.com/tngan/express-saml2/blob/master/examples/sp1/routes/sso.js#L86-L90

**Comment by mikevbaker** [comment]
Thanks @tngan that's the spot where I was looking, there's a similar spot in SP2. 
We're not using express, I don't have a router. But I understand that the `sp` object there is the ServiceProvider so I think I can adapt. Luckily the original author of the site has some time today and he's going to look at it with me. I'll let you know how it goes.

Thanks,
Mike

**Comment by tngan** [comment]
@mikevbaker This issue is closed because there is no response after 3 weeks. Feel free to reopen it if you have any updated. :)
