### ISSUE TITLE
NameIDFormat incorrectly replaced

### ISSUE THREAD

**Issue by vbakke** [tngan/express-saml2#67]
In RedirectBinding.js, loginRequestRedirectURL() the replace for NameIDFormat is:

NameIDFormat: namespace.format[spSetting.logoutNameIDFormat] || namespace.format.emailAddress,

Is spSetting.logoutNameIDFormat the correct attribute?

**Comment by tngan** [comment]
@vbakke Good catch, it should be `loginNameIDFormat`.
