### ISSUE TITLE
<EncryptedAssertion> is not replaced correctly

### ISSUE THREAD

**Issue by vbakke** [tngan/express-saml2#69]
In SamlLib.js, the function decryptAssertion(type, here, from, entireXML, callback) fails replacing <saml:EncryptedAssertion>, if the element contains any attributes, e.g. namespace attributes, such as this real life case:
>    <saml:EncryptedAssertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
   
My case was solved by changing:
> .replace('<saml:EncryptedAssertion>', '')

with a reg exp search:
> .replace(/<saml:EncryptedAssertion[^>]*>/, '')

However, doing text matches on XML with namespaces is not robust, because the prefix could just as well have been:
>    <assert:EncryptedAssertion xmlns:assert="urn:oasis:names:tc:SAML:2.0:assertion">

**Comment by tngan** [comment]
@vbakke Nice catch, there is another issue similar to this one in encryptAssertion. By the way, it would be good if you can make pull request, I am always appreciated that. :)

**Comment by vbakke** [comment]
Ok, I'll try. At least bigger changes. 
One liners might be easier to do without the extra branches, merges and pulling. :)
