### ISSUE TITLE
Decrypt Assertion, mismatch?

### ISSUE THREAD

**Issue by vbakke** [tngan/express-saml2#70]
I guess this is more of a question, than anything else.  It might be a bug, the documentation might need some clarification, or I've just doen something wrong. :)

### Service Provider settings (my side)
After an SP initiated AuthnRequest, I receive an Encrypted SamlResponse.  It has been encrypted by the IdP using the my public key, which was included in my metadatafile. That is:
```javascript
var spSetting = { ...
    privateKeyFile: './cert/private-key.pem',
    privateKeyFilePass: 'xxxx'
};
var sp = saml.ServiceProvider(spSetting);
sp.exportMetadata('./metadata/sso_metadata_sp.xml');
```

### Identity Provider settings (other side)
In my case, I have to use the same private key, when decrypting the SamlResponse from the IdP.  

The way I understand the [docs](https://express-saml2.js.org/encrypted_assertion.html), I need to specify:

```javascript
 var idpSetting = {
    isAssertionEncrypted: true,
    encPrivateKeyFile:  './cert/private-key.pem',
    encPrivateKeyFilePass: 'xxxx'
};
var idp = saml.IdentityProvider(idpSetting, './metadata/idp-metadata.xml');
```

### Decrypt
Now deep diving into SamlLib.js, `decryptAssertion(type, here, from, entireXML, callback)`
```javascript
xmlenc.decrypt(encryptedData, {
   // use this entity's private to decrypt
   key: Utility.readPrivateKeyFromFile(hereSetting.encPrivateKeyFile, hereSetting.encPrivateKeyFilePass) 
```

The variable `here.entitySetting` contains SPs `privateKeyFile`, and `from.entitySetting` contains `encPrivateKeyFile`. 
But we are reading the variable `here.entitySetting.encPrivateKeyFile`.

### What is wrong?
There are several candidates for change, I guess. 
Maybe the code should be using either `from.entitySetting.encPrivateKeyFile`?
Or `here.entitySetting.privateKeyFile`, and update the docs?
Or define `encPrivateKeyFile` in the spSetting?

**Comment by tngan** [comment]
For response signature, IdP uses it's private key to sign the response and SP uses IdP's cert to verify the signature.

For response encryption, IdP uses SP's cert for encryption to encrypt the response and SP uses SP's encryption private key to decrypt it.

This part of documentation has problem, the `encPrivateKeyFile` and `encPrivateKeyFilePass` should be set in SP's construction instead of IdP's construction.

**Comment by vbakke** [comment]
Brilliant! Thank you! Then I will do accordingly in my project, so that I don't get a surprise when we upgrade. :)

**Comment by tngan** [comment]
@vbakke Let me close this issue first. Re-open if needed.

**Comment by sai-frogo** [comment]
> For response signature, IdP uses it's private key to sign the response and SP uses IdP's cert to verify the signature.
> 
> For response encryption, IdP uses SP's cert for encryption to encrypt the response and SP uses SP's encryption private key to decrypt it.
> 
> This part of documentation has problem, the `encPrivateKeyFile` and `encPrivateKeyFilePass` should be set in SP's construction instead of IdP's construction.

Thank You
