### ISSUE TITLE
Invalid signature after decrypting SamlAssertion

### ISSUE THREAD

**Issue by vbakke** [tngan/express-saml2#71]
Sorry, me again. :) But this time I don't have a suggested solution.  :-/

I receive an encrypted SamlResponse, that [SamlTool validates](https://www.samltool.com/validate_response.php) as OK, given the IdP certificate, and my private key. 
However, it does not validate the decrypted file.

When SamTool decrypts the file, I get a slightly different result, then when I decrypt with express-saml2. 

The express-saml2 stops with the error message:
>Error: invalid signature: for uri #s22bedd198efd004dfff0b7aaf262d7144a81737be calculated digest is bWi39A0An6TWdnxr5FJJNZnkteg= but the xml to validate supplies digest rrW6cELtwOggZggY9ylh6EaHoDg=

I have tried to manually update the xml-cert to 0.9.0 (express-saml2 package.json specifies 0.8.5).

**Comment by vbakke** [comment]
Feel free to look at my test data. (It contains only test certificates and keys, but I don't see any reason for uploading these to GitHub.

https://www.dropbox.com/s/nhjakgxka1ss2x9/express-saml2-verification.zip?dl=0

Please notify me if you download the ZIP-file, and I will remove the file from Dropbox.


Regards,
Vegard :)

**Comment by tngan** [comment]
@vbakke Make sure it's for testing use only. I have crossed out the link in your comment after I have downloaded.

**Comment by vbakke** [comment]
Thank you. I know. It is only now for development. Even the test environment will have different keys when we get the SAML integration working. :)

**Comment by tngan** [comment]
I have checked the decrypted response, it contains both signature assertion In v1, we don't have validation on the signature of entire response message, but we would handle it in v2. (#64). 

I will make a test in v2 as well. I closed this issue because v1 will be deprecated very soon.

**Comment by vbakke** [comment]
Ah, so _that_ was why. :)
Are you saying the branch 2.0.0-beta already has support for this? Or that it will have soon?
(I'm just asking for my testing purposes. : )

**Comment by tngan** [comment]
It's already in v2.0.0-beta.
